server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org:
      springframework:
        web: INFO
        security: INFO
      hibernate: INFO